FROM openjdk:11

run apt-get update && apt-get install -y telnet

ARG JAR_FILE=build/libs/*all*.jar

WORKDIR /app

COPY ${JAR_FILE} /app/app.jar

ENV KAFKA_TOPIC=${KAFKA_TOPIC:-defaultfromdockerfile}
ENV KAFKA_BROKER_HOST=${KAFKA_BROKER_HOST:-defaultfromdockerfile}
ENV KAFKA_BROKER_PORT=${KAFKA_BROKER_PORT:-defaultfromdockerfile}

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
