version: "3"

services:

  producer:
    container_name: producer    
    build:
      context: .
      dockerfile: Dockerfile.producer
    environment:
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_BROKER_HOST: ${KAFKA_BROKER_HOST}
      KAFKA_BROKER_PORT: ${KAFKA_BROKER_PORT}
