apiVersion: v1
kind: Service
metadata:
  name: broker-monitoring-web
  namespace: data-agrigator
  labels:
    app: control-center
    tier: broker
spec:
  type: NodePort
  selector:
    app: control-center
  ports:
    - name: control-center
      port: 9021
      targetPort: 9021
      protocol: TCP
      nodePort: 30021
