apiVersion: v1
kind: Service
metadata:
  name: broker-monitoring
  namespace: data-agrigator
  labels:
    app: control-center
    tier: broker
spec:
  type: ClusterIP
  selector:
    app: control-center
  ports:
    - name: control-center
      port: 9021
      protocol: TCP
