FROM flink:1.17-scala_2.12

COPY /kafka-flink-postgresql-gradle/build/libs/kafka-flink-postgresql-gradle-0.1-SNAPSHOT-all.jar /opt/flink/usrlib/my_api.jar

ENV FLINK_PROPERTIES=""
ENV jobmanager.rpc.address=jobmanager
ENV taskmanager.numberOfTaskSlots=2
ENV parallelism.default=2

CMD ["taskmanager"] 
