version: "3"

services:

  producer:
    container_name: producer    
    build:
      context: .
      dockerfile: Dockerfile.crawler-producer
    environment:
      TOPIC_KAFKA: protobuf-data
      HOST_KAFKA: localhost
      PORT_KAFKA: 9092
