FROM openjdk:11-jdk

ARG JAR_FILE=build/libs/*all*.jar

WORKDIR /app

COPY ${JAR_FILE} /app/app.jar

ENV TOPIC_KAFKA=default-topic
ENV HOST_KAFKA=localhost
ENV PORT_KAFKA=9092

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
