apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: data-agrigator
  labels:
    app: kafka-kraft
    tier: broker
spec:
  selector:
    app: kafka-kraft
  ports:
    - name: kafka-kraft
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: jmx
      port: 9091
      targetPort: 9091
      protocol: TCP
