apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    app: kafka
spec:
  selector:
    app: kafka
    role: broker
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
