apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-monitoring
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-monitoring
  template:
    metadata:
      labels:
        app: kafka-monitoring
    spec:
      containers:
        - name: kafka-monitoring
          image: confluentinc/cp-enterprise-control-center:7.4.1
          ports:
            - containerPort: 9021
          env:
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: 'kafka-broker-service.default.svc.cluster.local:29092'
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: '1'
            - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
              value: '1'
            - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
              value: '1'
            - name: CONFLUENT_METRICS_TOPIC_REPLICATION
              value: '1'
            - name: PORT
              value: '9021'      
