FROM postgres:15.3-alpine

COPY ./database/db_scripts/create_table.sql /docker-entrypoint-initdb.d/create_table.sql

ENV POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB do not set}
ENV POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER do not set}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD do not set}

EXPOSE 5432
