FROM postgres:15.3-alpine

COPY ./db_scripts/create_table.sql /docker-entrypoint-initdb.d/create_table.sql

ENV POSTGRES_DB=${DATABASE_NAME:-defaultfromdockerfile}
ENV POSTGRES_USER=${DATABASE_USER:-defaultfromdockerfile}
ENV POSTGRES_PASSWORD=${DATABASE_PASSWORD:-defaultfromdockerfile}

EXPOSE 5432
