apiVersion: v1
kind: Service
metadata:
  namespace: data-agrigator
  name: database
  labels:
    app: postgres
    tier: database
spec:
  selector:
    app: postgres
  ports:
  - name: database
    port: 5432
    protocol: TCP
  
