version: "3"
services:

  jobmanager:
    container_name: consumer-jobmanager
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: Dockerfile.consumer-jobmanager
    environment:
      TOPIC: protobuf-data
      KAFKA_GROUP: protobuf-data
      KAFKA_HOST_NAME: broker
      KAFKA_PORT: 9092
      DATABASE_HOST_NAME: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: crawler
      DATABASE_PASSWORD: 1111

  taskmanager:
    container_name: consumer-taskmanager
    depends_on:
      - jobmanager
    build:
      context: .
      dockerfile: Dockerfile.consumer-jobmanager
    environment:
      TOPIC: protobuf-data
      KAFKA_GROUP: protobuf-data
      KAFKA_HOST_NAME: broker
      KAFKA_PORT: 9092
      DATABASE_HOST_NAME: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: crawler
      DATABASE_PASSWORD: 1111
    
