
CREATE TABLE IF NOT EXISTS stories(
id CHARACTER VARYING(100) NOT NULL UNIQE, 
title CHARACTER VARYING(189819) NOT NULL,
url CHARACTER VARYING(189819) NOT NULL,
site CHARACTER VARYING(189819) NOT NULL,
time TIMESTAMP NOT NULL,
favicon_url CHARACTER VARYING(189819) NOT NULL,
similar_stories CHARACTER VARYING(189819),
description CHARACTER VARYING(189819)
);

CREATE TABLE IF NOT EXISTS tags(
id BIGSERIAL PRIMARY KEY  NOT NULL,
id_story CHARACTER VARYING(100) REFERENCES stories(id) ON DELETE CASCADE  NOT NULL,
tag CHARACTER VARYING(189819) NOT NULL
);

CREATE TABLE IF NOT EXISTS similar_stories(
id BIGSERIAL PRIMARY KEY  NOT NULL,
id_story CHARACTER VARYING(100) REFERENCES stories(id) ON DELETE CASCADE  NOT NULL,
similar_story CHARACTER VARYING(189819) NOT NULL
);

