
CREATE TABLE IF NOT EXISTS newses(
id BIGSERIAL PRIMARY KEY  NOT NULL,
title CHARACTER VARYING(189819) NOT NULL,
text TEXT NOT NULL,
link CHARACTER VARYING(189819) NOT NULL,
hash_news INT NOT NULL
);

CREATE TABLE IF NOT EXISTS tags(
id BIGSERIAL PRIMARY KEY  NOT NULL,
id_news BIGINT REFERENCES newses(id) ON DELETE CASCADE,
tag CHARACTER VARYING(189819) NOT NULL
);

