apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: anatoliysharov/producer:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_TOPIC
              value: 'my-topic'
            - name: KAFKA_BROKER_HOST
              value: 'localhost'
            - name: KAFKA_BROKER_PORT
              value: '9092'
